Update update-arch

diff --git a/bin/update-arch b/bin/update-arch
--- a/bin/update-arch
+++ b/bin/update-arch
@@ -32,6 +32,7 @@ Sync=""
 LoggingOff=""
 RSSOff=""
 PacOff=""
+NamCapOff=""
 Tmux=""
 Arguments=""
 Shutdown=""
@@ -62,9 +63,10 @@ function help {
     echo "  --sleep         Suspend computer if the script finished without error"
     echo "  --logoff        Logout if the script finished without error"
     echo "  -s, --sync      Refresh and synchronize normal package databases"
-    echo "  -y, --refresh   Force the refresh of package databases" 
+    echo "  -y, --refresh   Force the refresh of package databases"
+    echo "  -n, --nonamcap  Disable checking packages with namcap"
     echo "  -r  --norss     Disable checking for archlinux news"
-    echo "  -t, --tmux      Run this script in a tmux session"   
+    echo "  -t, --tmux      Run this script in a tmux session" 
     echo "  -p, --nopac     Disable checking for pacnew files" 
     echo "  -i, --install   Install a package"
     echo "  -b, --build     Build a package"
@@ -79,7 +81,7 @@ function usage {
 }
 
 #testing number of args:
-if [ "${#}" -gt 11 ]; then
+if [ "${#}" -gt 12 ]; then
     echo -e $red"Error:$reset Invalid number of parameters"
     echo ""
     usage
@@ -178,7 +180,15 @@ if [ -n "$1" ]; then #non-empty
         echo -e $red"Error:$reset Invalid arguments '${Args}'"
         echo ""
 		usage
-	  fi  
+	  fi
+    elif [[ $PARAM =~ ^--[Nn][Oo][Nn][Aa][Mm][Cc][Aa][Pp]$ ]] || [[ $PARAM =~ ^-[Nn]$ ]]; then
+      if [[ $NamCapOff == "" ]]; then
+        NamCapOff="Yes"
+	  else
+        echo -e $red"Error:$reset Invalid arguments '${Args}'"
+        echo ""
+		usage
+	  fi 
     elif [[ $PARAM =~ ^--[Pp][Oo][Ww][Ee][Rr][Oo][Ff][Ff]$ ]] || [[ $PARAM =~ ^--[Ss][Hh][Uu][Tt][Dd][Oo][Ww][Nn]$ ]] || [[ $PARAM =~ ^-[Oo]$ ]]; then
       if [[ $Sleep == "" ]] && [[ $Shutdown == "" ]] && [[ $Reboot == "" ]] && [[ $Hibernate == "" ]] && [[ $Logout == "" ]]; then
         Shutdown="Yes"
@@ -220,7 +230,7 @@ if [ -n "$1" ]; then #non-empty
         echo ""
 		usage
 	  fi
-    elif [[ $PARAM =~ ^-[AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy][AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy][AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmOoPpRrSsTtUuYy]?$ ]]; then
+    elif [[ $PARAM =~ ^-[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy][AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy][AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?[AaBbEeFfGgIiLlMmNnOoPpRrSsTtUuYy]?$ ]]; then
       i=1
 	  while (( i++ < ${#PARAM} ))
 	  do
@@ -305,6 +315,14 @@ if [ -n "$1" ]; then #non-empty
 				echo ""
 				usage
 			fi
+        elif [[ $char =~ [Nn] ]]; then
+			if [[ $NamCapOff == "" ]]; then
+				NamCapOff="Yes"
+			else
+				echo -e $red"Error:$reset Invalid arguments '${Args}'"
+				echo ""
+				usage
+			fi
         elif [[ $char =~ [Uu] ]]; then
             if [[ $Sleep == "" ]] && [[ $Shutdown == "" ]] && [[ $Reboot == "" ]] && [[ $Hibernate == "" ]] && [[ $Logout == "" ]]; then
                 Sleep="Yes"
@@ -365,6 +383,18 @@ if [[ $Help == "Yes" ]]; then
     exit 0
 fi
 
+if [[ $AUR == "Yes" ]]; then
+    Sync="Yes"
+fi
+
+if [[ $Refresh == "Yes" ]] && [[ ! $Sync == "Yes" ]] && [[ ! $AUR == "Yes" ]]; then
+    usage
+fi
+
+if [[ ! $Build == "Yes" ]] && [[ ! $Install == "Yes" ]] && [[ ! $Mirror == "Yes" ]] && [[ ! $AUR == "Yes" ]] && [[ ! $Sync == "Yes" ]]; then
+    usage
+fi
+
 if [[ $Tmux == "Yes" ]]; then
     if [ $EUID -ne 0 ]; then
         if [ "$TERM" = "screen" ] && [ -n "$TMUX" ]; then #checking if script is running from a tmux session
@@ -399,6 +429,9 @@ if [[ $Tmux == "Yes" ]]; then
             if [[ $PacOff == "Yes" ]]; then
                 Arguments="${Arguments}p"
             fi
+            if [[ $NamCapOff == "Yes" ]]; then
+                Arguments="${Arguments}n"
+            fi
             if [[ $Sleep == "Yes" ]]; then
                 Arguments="${Arguments}u"
             fi
@@ -424,55 +457,7 @@ if [[ $Tmux == "Yes" ]]; then
     fi
 fi
 
-if [[ $AUR == "Yes" ]]; then
-    Sync="Yes"
-fi
-
-if [[ $Install == "" ]]; then
-	Install="No"
-fi
-
-if [[ $Build == "" ]]; then
-	Build="No"
-fi
-
-if [[ $Mirror == "" ]]; then
-	Mirror="No"
-fi
-
-if [[ $Refresh == "" ]]; then
-	Refresh="No"
-fi
-
-if [[ $AUR == "" ]]; then
-	AUR="No"
-fi
-
-if [[ $Sync == "" ]]; then
-	Sync="No"
-fi
-
-if [[ $LoggingOff == "" ]]; then
-	LoggingOff="No"
-fi
-
-if [[ $RSSOff == "" ]]; then
-	RSSOff="No"
-fi
-
-if [[ $PacOff == "" ]]; then
-	PacOff="No"
-fi
-
-if [[ $Refresh == "Yes" ]] && [[ $Sync == "No" ]] && [[ $AUR == "No" ]]; then
-    usage
-fi
-
-if [[ $Build == "No" ]] && [[ $Install == "No" ]] && [[ $Mirror == "No" ]] && [[ $AUR == "No" ]] && [[ $Sync == "No" ]]; then
-    usage
-fi
-
-if [[ $PacOff == "No" ]]; then
+if [[ ! $PacOff == "Yes" ]]; then
   echo
   echo -e $blue"===>$reset Checking for pacnew files..."
   echo
@@ -489,7 +474,7 @@ if [[ $PacOff == "No" ]]; then
   echo
   echo
 fi
-if [[ $RSSOff == "No" ]]; then
+if [[ ! $RSSOff == "Yes" ]]; then
   [ -f $RSSFILE ] && cat "${RSSFILE}" 2> /dev/null
   /usr/bin/rm -f "${TMPFILE}"
   echo
@@ -533,36 +518,39 @@ if [[ $Mirror == "Yes" ]]; then
 fi
 if [[ $Install == "Yes" ]] || [[ $Build == "Yes" ]]; then
     if [[ $Build == "Yes" ]]; then
-        echo
-        echo -e $blue"===>$reset Checking PKGBUILD file for error..."
-        echo ""
-        /usr/bin/namcap PKGBUILD
-        echo ""
-        read -p "Press enter to continue..."
+        if [[ ! $NamCapOff == "Yes" ]]; then
+            echo
+            echo -e $blue"===>$reset Checking PKGBUILD file for error..."
+            echo ""
+            /usr/bin/namcap PKGBUILD
+            echo ""
+            read -p "Press enter to continue..."
+        fi
         echo ""
         echo -e $blue"===>$reset Building the package..."
         echo ""
-        { /usr/bin/sudo -u $USERNAME /usr/bin/makepkg -sc ; } || { echo -e $red"Error:$reset Cannot build the package" ; exit 1; }
-    fi    
-    echo ""
-    echo -e $blue"===>$reset Checking the build package file for error..."
-    echo ""
-    /usr/bin/find . -maxdepth 1 -name '*.pkg.tar.xz' -exec /usr/bin/namcap {} \;
-    echo ""
-    read -p "Press enter to continue..."
+        { /usr/bin/sudo -u $USERNAME /usr/bin/makepkg -sc ; } || { echo "" ; echo -e $red"Error:$reset Cannot build the package" ; exit 1; }
+    fi
+    if [[ ! $NamCapOff == "Yes" ]]; then
+        echo ""
+        echo -e $blue"===>$reset Checking the build package file for error..."
+        echo ""
+        /usr/bin/find . -maxdepth 1 -name '*.pkg.tar.xz' -exec /usr/bin/namcap {} \;
+        echo ""
+        read -p "Press enter to continue..."
+    fi
     if [[ $Install == "Yes" ]]; then
         echo ""
         echo -e $blue"===>$reset Installing the package..."
         echo ""
-        { /usr/bin/find . -maxdepth 1 -name '*.pkg.tar.xz' -exec $SUDO /usr/bin/pacman -U {} \; ; } || { echo -e $red"Error:$reset Cannot install the package" ; exit 1; }
-        #{ $SUDO /usr/bin/pacman -U "$(ls *.pkg.tar.xz 2> /dev/null)" ; } || { echo -e $red"Error:$reset Cannot install the package" ; exit 1; }
+        { /usr/bin/find . -maxdepth 1 -name '*.pkg.tar.xz' -exec $SUDO /usr/bin/pacman -U {} \; ; } || { echo "" ; echo -e $red"Error:$reset Cannot install the package" ; exit 1; }
     fi
 fi	
 if [[ $Sync == "Yes" ]]; then
 	echo
 	echo -e $blue"===>$reset Checking for updates..."
 	echo
-	if [[ $Refresh == "No" ]]; then
+	if [[ ! $Refresh == "Yes" ]]; then
 	  if [[ $AUR == "Yes" ]]; then
 	    if [ -x /usr/bin/yaourt ]; then
             { /usr/bin/sudo -u $USERNAME /usr/bin/yaourt -Syua ; } || { echo -e $red"Error:$reset Cannot update the system" ; exit 1; }
@@ -591,11 +579,11 @@ if [[ $Sync == "Yes" ]]; then
     fi
 fi
 echo
-if [[ $RSSOff == "No" ]]; then
+if [[ ! $RSSOff == "Yes" ]]; then
   [ -f $RSSFILE ] && cat "${RSSFILE}" | 2> /dev/null
 fi
 echo
-if [[ $LoggingOff == "No" ]]; then
+if [[ ! $LoggingOff == "Yes" ]]; then
   echo
   echo -e  $blue"===>$reset Updating log files..."
   echo
@@ -603,7 +591,7 @@ if [[ $LoggingOff == "No" ]]; then
   { /usr/bin/sudo -u $USERNAME /usr/bin/tail --lines=100 /var/log/pacman.log > $HOMEDIR/.updatesystem.log ; } || { echo -e $red"Error:$reset Cannot update '.updatesystem.log' file" ; }
 fi
 echo
-if [[ $RSSOff == "No" ]]; then
+if [[ ! $RSSOff == "Yes" ]]; then
   echo
   echo "Latest arch linux news:"
   echo
