Update update-arch

diff --git a/bin/update-arch b/bin/update-arch
--- a/bin/update-arch
+++ b/bin/update-arch
@@ -366,6 +366,11 @@ if [[ $Help == "Yes" ]]; then
 fi
 
 if [[ $Tmux == "Yes" ]]; then
+    if [ $EUID -eq 0 ]; then
+        echo -e $red"error:$reset You cannot start a tmux session as root."
+        exit 1
+    fi
+    
     if [[ $Sync == "Yes" ]]; then
         Arguments="${Arguments}s"
     fi
